### ISSUE TITLE
Looping with boss count

### ISSUE THREAD

**Issue by GreenComfyTea** [nistaux/MHRise-Overlay-Ultrawide#1]
`for i = 0, total_monster do` should be `for i = 0, total_monster - 1 do` because LUA is using 1-based indexing, while C# (managed part of MHR) is using 0-based indexing. Good work nonetheless!

**Comment by nistaux** [comment]
> `for i = 0, total_monster do` should be `for i = 0, total_monster - 1 do` because LUA is using 1-based indexing, while C# (managed part of MHR) is using 0-based indexing. Good work nonetheless!

Ill fix that now! Thanks
